### ISSUE TITLE
ImportError: libtorch.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gachiemchiep** [timy90022/One-Shot-Object-Detection#15]
Hello @timy90022 
Thank you for your great work

When trying your code, i had the following error: 

```bash
$ python test_net.py --s 1  --g 1 --a 4 --cuda
Traceback (most recent call last):
  File "test_net.py", line 26, in <module>
    from model.roi_layers import nms
  File "/home/gachiemchiep/workspace/github/One-Shot-Object-Detection/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/gachiemchiep/workspace/github/One-Shot-Object-Detection/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: libtorch.so: cannot open shared object file: No such file or directory
```
Do you have any idea about this error ?

**Comment by sisrfeng** [comment]
hi，how did you solve it?

**Comment by gachiemchiep** [comment]
Hi @sisrfeng 
I search for the libtorch.so and add its path into system search path. 
I forgot the detail but something similar to this

```bash
# Find the libtorch.so
sudo ldconfig -p | grep libtorch.so
# Add to user path
# Add this line to ~/.bashrc
export LD_LIBRARY_PATH="${THE PATH HERE}:$LD_LIBRARY_PATH"

```
