### ISSUE TITLE
What `coco_{}_e2e_mask_rcnn_R_101_FPN_1x_caffe2.pkl` means & how to fix?

### ISSUE THREAD

**Issue by Soarkey** [timy90022/One-Shot-Object-Detection#24]
Hi, thanks for your contribution first.
Now I face some trouble when run this project.  The following is the error log:

```shell
loading annotations into memory...
Done (t=16.83s)
creating index...
index created!
No reference file.
Traceback (most recent call last):
  File "trainval_net.py", line 195, in <module>
    seen=args.seen)
  File "/data/One-Shot-Object-Detection/lib/roi_data_layer/roidb.py", line 165, in combined_roidb
    imdb, roidb, query, reserved = get_roidb(s, training)
  File "/data/One-Shot-Object-Detection/lib/roi_data_layer/roidb.py", line 147, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/data/One-Shot-Object-Detection/lib/datasets/factory.py", line 67, in get_imdb
    return __sets[name]()
  File "/data/One-Shot-Object-Detection/lib/datasets/factory.py", line 37, in <lambda>
    __sets[name] = (lambda split=split, year=year: coco(split, year))
  File "/data/One-Shot-Object-Detection/lib/datasets/coco.py", line 92, in __init__
    assert False
AssertionError
```

I found associated code line is like following:
```python
        coco_name = image_set + year  # e.g., "val2014"
        self._data_name = (self._view_map[coco_name]
                           if coco_name in self._view_map
                           else coco_name)
        # Dataset splits that have ground-truth annotations (test splits
        # do not have gt annotations)
        self._gt_splits = ('train', 'val', 'minival')

        # set reference file
        self._reference_dir = os.path.join(cfg.DATA_DIR, "coco_reference_image")
        self._reference_file = os.path.join(self._reference_dir,
                                            "coco_{}_e2e_mask_rcnn_R_101_FPN_1x_caffe2.pkl".format(
                                                self._data_name))
        if not os.path.exists(self._reference_file): # ! error occur ! 
            print('No reference file.')
            assert False
        else:
            with open(self._reference_file, "rb") as f:
                self.reference_image = pickle.load(f)
```

What `coco_{}_e2e_mask_rcnn_R_101_FPN_1x_caffe2.pkl` means?  Could you tell me how to fix this issue? 
Thanks!

**Comment by danielcrane** [comment]
Have you tried following Step 4 of the README? https://github.com/timy90022/One-Shot-Object-Detection#4-reference-images

**Comment by Soarkey** [comment]
ok, i got it! 
thanks!
