### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Superwen1017** [timy90022/One-Shot-Object-Detection#26]
Traceback (most recent call last):
  File "trainval_net.py", line 305, in <module>
    data = next(data_iter)
  File "/data/zww/anaconda3/envs/zwwpac/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 568, in __next__
    return self._process_next_batch(batch)
  File "/data/zww/anaconda3/envs/zwwpac/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/data/zww/anaconda3/envs/zwwpac/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/zww/anaconda3/envs/zwwpac/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/zww/test/One-Shot-Object-Detection-master/lib/roi_data_layer/roibatchLoader.py", line 106, in __getitem__
    catgory = blobs['gt_boxes'][:,-1]
IndexError: too many indices for array

**Comment by john2020-210** [comment]
I have miss the same problem ,how can you solve that?

**Comment by john2020-210** [comment]
I have met the same problem, have you solved it?
